Change TTL indexes to packet.added key
moscajs/aedes-persistence-mongodb pull request #51
Opened 2020-08-17 19:11 UTC by schwing

- Change index key from `packet` to `packet.added` on the `will`, `outgoing`, and `incoming` collections.

Fixes https://github.com/moscajs/aedes-persistence-mongodb/issues/50

2020-08-18 06:22 UTC, robertsLando commented
@schwing I would add a test here too: https://github.com/moscajs/aedes-persistence-mongodb/blob/master/test.js#L517

Just add some packets to other collections and check if them are removed like we are doing with retained collection now

2020-08-18 16:51 UTC, schwing commented
@robertsLando Thanks, I didn't notice those other tests before. I've added tests for all the collections there and also for the index tests for better coverage.

I'm unable to reproduce the latest CI test failures shown for 10.x or 13.x here. Is this possibly a timing issue where `ready` is sometimes emitted prior to indexes being created because the `createIndex()` calls don't wait for callbacks here? https://github.com/moscajs/aedes-persistence-mongodb/blob/master/persistence.js#L97-L116

2020-08-19 06:55 UTC, robertsLando requested changes

2020-08-19 06:55 UTC, robertsLando commented on test.js
> +              })
Try to place this inside a `setImmediate` just to try :)

2020-08-19 06:58 UTC, robertsLando commented
> Is this possibly a timing issue where ready is sometimes emitted prior to indexes being created because the createIndex() calls don't wait for callbacks here?

It could be the reason, could you try to fix that?

2020-08-19 15:50 UTC, robertsLando commented
@schwing I think it would be better to add callbacks support for create index. YOu could use `fastparallel` https://www.npmjs.com/package/fastparallel

2020-08-19 15:52 UTC, schwing commented
@robertsLando Agreed. I'll add that.

2020-08-19 19:04 UTC, schwing commented
Added and tests look good now. I attempted to match style with the rest of the module. Let me know any thoughts.

2020-08-19 19:05 UTC, robertsLando approved these changes
LGTM. Waiting also @mcollina review before merging. Nice work @schwing thanks for the contribution 😄

2020-08-20 06:19 UTC, mcollina approved these changes
lgtm

2020-08-20 07:48 UTC, merged

2020-08-20 07:54 UTC, robertsLando commented
@schwing Just released a new patch version with this fix :+1:

2020-08-20 14:26 UTC, schwing commented
Great! Thanks for all the assistance here.